version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(ci):"

  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(ci):"

  - package-ecosystem: npm
    directory: /islands
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(ci):"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci):"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci):"
