"""add github metadata fields to project

Revision ID: 89895fed1f49
Revises: 71337974e647
Create Date: 2026-02-27 14:21:53.829332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '89895fed1f49'
down_revision = '71337974e647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_stars', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('github_language', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('project', sa.Column('github_forks', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('github_last_pushed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'github_last_pushed_at')
    op.drop_column('project', 'github_forks')
    op.drop_column('project', 'github_language')
    op.drop_column('project', 'github_stars')
    # ### end Alembic commands ###
